services:
  web:
    image: registry.paulnaszalyi.fr/mediaspot:latest
    ports:
      - "3538:80"
    container_name: mediaspot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediaspot.rule=Host(`mediaspot.paulnaszalyi.fr`)"
      - "traefik.http.routers.mediaspot.tls=true"
      - "traefik.http.routers.mediaspot.tls.certresolver=letsencrypt"
      - "traefik.http.services.mediaspot.loadbalancer.server.port=80"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
